root: true
env:
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
- '@typescript-eslint'
- 'react'
- 'react-hooks'
extends:
- 'eslint:recommended'
- 'plugin:@typescript-eslint/recommended'
- 'plugin:react/recommended'
- 'plugin:react-hooks/recommended'
